input: doc
output: _build
requirements: requirements.txt
target: gh-pages
formats: [ html ]
images:
  base: ghcr.io/hdl/containers/doc
theme: https://codeload.github.com/buildthedocs/sphinx.theme/tar.gz/v1
