name: 'base'

on:
  push:
  schedule:
    - cron: '0 0 * * 5'

env:
  CI: true
  DOCKER_BUILDKIT: 1
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

jobs:

  base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build images
      run: |
        docker build -t symbiflow/build:base --target base - < base.dockerfile
        docker build -t symbiflow/build:build --target build - < base.dockerfile
        docker build -t symbiflow/build:dev - < base.dockerfile
    - name: Deploy to hub.docker.com
      run: |
        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
        docker push symbiflow/build:base
        docker push symbiflow/build:build
        docker push symbiflow/build:dev
        docker logout
