name: 'formal'

on:
  push:
  schedule:
    - cron: '0 0 * * 5'

env:
  CI: true
  DOCKER_BUILDKIT: 1
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

jobs:

  formal:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build images
      run: |
        docker build -t symbiflow/formal:ghdl --build-arg IMAGE="ghdl/synth:beta" - < formal.dockerfile
        docker build -t symbiflow/formal --build-arg IMAGE="symbiflow/yosys" - < formal.dockerfile
    - name: Deploy to hub.docker.com
      run: |
        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
        docker push symbiflow/formal:ghdl
        docker push symbiflow/formal
        docker logout
