name: 'nextpnr'

on:
  push:
  schedule:
    - cron: '0 0 * * 5'

env:
  CI: true
  DOCKER_BUILDKIT: 1
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

jobs:

  nextpnr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build images
      run: |
        docker build -t symbiflow/nextpnr:ice40 --target=ice40 - < nextpnr.dockerfile
        docker build -t symbiflow/nextpnr:ecp5 --target=ecp5 - < nextpnr.dockerfile
        docker build -t symbiflow/nextpnr - < nextpnr.dockerfile
    - name: Deploy to hub.docker.com
      run: |
        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
        docker push symbiflow/nextpnr:ice40
        docker push symbiflow/nextpnr:ecp5
        docker push symbiflow/nextpnr
        docker logout
