name: 'test'

on:
  push:
  schedule:
    - cron: '0 0 * * 5'

env:
  CI: true
  DOCKER_BUILDKIT: 1
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

jobs:

  test:
    #needs: [ pnr, yosys ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./test_pnr.sh
