# Authors:
#   Unai Martinez-Corral
#
# Copyright 2021 Unai Martinez-Corral <unai.martinezcorral@ehu.eus>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

HDLC: 0
defaults:
  images:
    build/base:
      dockerfile: base
      target: base
    build/build:
      dockerfile: base
      target: build
    build/dev:
      dockerfile: base
    pkg/boolector:
      target: ''
    pkg/cvc:
      target: ''
    formal/min:
      dockerfile: formal
      target: min
    formal:
      target: latest
    formal/all:
      dockerfile: formal
    ghdl/yosys:
      dockerfile: ghdl-yosys-plugin
    pkg/ghdl:
      target: pkg-mcode
    pkg/ghdl/llvm:
      dockerfile: ghdl
      target: pkg-llvm
    ghdl:
      target: mcode
    ghdl/llvm:
      dockerfile: ghdl
      target: llvm
    build/impl:
      dockerfile: impl
      target: base
    impl/ice40:
      dockerfile: impl
      target: ice40
    impl/icestorm:
      dockerfile: impl
      target: icestorm
    impl/ecp5:
      dockerfile: impl
      target: ecp5
    impl/prjtrellis:
      dockerfile: impl
      target: prjtrellis
    impl/generic:
      dockerfile: impl
      target: generic
    impl/pnr:
      dockerfile: impl
      target: pnr
    build/nextpnr/base:
      dockerfile: nextpnr
      target: base
    build/nextpnr/build:
      dockerfile: nextpnr
      target: build
    pkg/nextpnr/ice40:
      dockerfile: nextpnr
      target: pkg-ice40
    nextpnr/ice40:
      dockerfile: nextpnr
      target: ice40
    nextpnr/icestorm:
      dockerfile: nextpnr
      target: icestorm
    pkg/nextpnr/nexus:
      dockerfile: nextpnr
      target: pkg-nexus
    nextpnr/nexus:
      dockerfile: nextpnr
      target: nexus
    nextpnr/prjoxide:
      dockerfile: nextpnr
      target: prjoxide
    pkg/nextpnr/ecp5:
      dockerfile: nextpnr
      target: pkg-ecp5
    nextpnr/ecp5:
      dockerfile: nextpnr
      target: ecp5
    nextpnr/prjtrellis:
      dockerfile: nextpnr
      target: prjtrellis
    pkg/nextpnr/generic:
      dockerfile: nextpnr
      target: pkg-generic
    nextpnr/generic:
      dockerfile: nextpnr
      target: generic
    sim/osvb:
      dockerfile: osvb
    pkg/pono:
      target: ''
    sim/scipy-slim:
      dockerfile: scipy
    sim/scipy:
      dockerfile: osvb
      argimg: sim/scipy-slim
    sim/octave-slim:
      dockerfile: octave
    sim/octave:
      dockerfile: osvb
      argimg: sim/octave-slim
    pkg/superprove:
      target: ''
    pkg/symbiyosys:
      target: ''
    pkg/yices2:
      target: ''
    pkg/z3:
      target: ''
