name: 'base'

on:
  push:
  schedule:
    - cron: '0 0 * * 5'

jobs:

  base:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build images
      run: |
        docker build -t symbiflow/build:base  --target base  - < base.dockerfile
        docker build -t symbiflow/build:build --target build - < base.dockerfile
        docker build -t symbiflow/build:dev - < base.dockerfile

    - name: Deploy to DockerHub
      run: |
        docker push symbiflow/build:base
        docker push symbiflow/build:build
        docker push symbiflow/build:dev
