name: 'base'

on:
  push:
  schedule:
    - cron: '0 0 * * 5'
  repository_dispatch:
    types: [ base ]

jobs:

  base:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build images
      run: |
        docker build -t hdlc/build:base  --target base  - < base.dockerfile
        docker build -t hdlc/build:build --target build - < base.dockerfile
        docker build -t hdlc/build:dev - < base.dockerfile

    - uses: docker://hdlc/build:base
      with:
        args: ./test/build--base.sh

    - uses: docker://hdlc/build:build
      with:
        args: ./test/build--build.sh

    - uses: docker://hdlc/build:dev
      with:
        args: ./test/build--dev.sh

    - name: Deploy to DockerHub
      run: |
        docker push hdlc/build:base
        docker push hdlc/build:build
        docker push hdlc/build:dev
