name: 'doc'

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/doc.yml'
      - 'doc/*'
  schedule:
    - cron: '0 0 * * 4'
  repository_dispatch:
    types: [ doc ]

jobs:

  asciidoc:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    # Equivalent local execution: docker run -v /$(pwd)/doc://documents/ asciidoctor/docker-asciidoctor asciidoctor index.adoc
    - name: Build site
      uses: docker://asciidoctor/docker-asciidoctor
      with:
        entrypoint: asciidoctor
        args: doc/index.adoc

    - name: Publish site to gh-pages (doc)
      if: github.event_name != 'pull_request'
      run: |
        mkdir pages
        cd pages
        git init
        cp ../.git/config ./.git/config
        touch .nojekyll
        mv ../doc/index.html ./
        git add .
        git config --local user.email "push@gha"
        git config --local user.name "GHA"
        git commit -am "update ${{ github.sha }}"
        git push -u origin +HEAD:gh-pages
