name: 'doc'

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/doc.yml'
      - 'doc/**'
      - 'graph/**'
  schedule:
    - cron: '0 0 * * 4'
  workflow_dispatch:
  repository_dispatch:
    types: [ doc ]

env:
  DOCKER_BUILDKIT: 1

jobs:

  asciidoc:
    runs-on: ubuntu-latest
    steps:

    - name: Build hdlc/doc:asciidoctor-py
      run: |
        docker build -t hdlc/doc:asciidoctor-py - <<-EOF
        FROM asciidoctor/docker-asciidoctor
        RUN apk add -U --no-cache graphviz python3 \
         && ln -s /usr/bin/python3 /usr/bin/python
        EOF

    - uses: actions/checkout@v2

    - name: Build site
      run: docker run --rm -v /$(pwd)://documents/ hdlc/doc:asciidoctor-py ./doc/make.sh

    - name: Publish site to gh-pages (doc)
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'
      run: |
        mkdir pages
        cd pages
        git init
        cp ../.git/config ./.git/config
        touch .nojekyll
        mv ../doc/index.html ./
        mv ../doc/*.svg ./
        mkdir img
        cp ../doc/img/icon.png ./img
        git add .
        git config --local user.email "push@gha"
        git config --local user.name "GHA"
        git commit -am "update ${{ github.sha }}"
        git push -u origin +HEAD:gh-pages

    - name: Login to DockerHub
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - run: dockerPush hdlc/doc:asciidoctor-py
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'
