name: 'formal'

on:
  push:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:
  repository_dispatch:
    types: [ formal ]

env:
  DOCKER_BUILDKIT: 1

jobs:

  formal:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - run: echo "$(pwd)/.github/bin" >> $GITHUB_PATH

    - run: dockerBuild hdlc/formal formal

    - run: dockerTest  hdlc/formal formal

    - run: dockerPush  hdlc/formal
