name: 'ghdl'

on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:
  repository_dispatch:
    types: [ ghdl ]

env:
  DOCKER_BUILDKIT: 1

jobs:

  ghdl:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - run: echo "$(pwd)/.github/bin" >> $GITHUB_PATH

    - run: dockerBuild hdlc/pkg:ghdl  ghdl  pkg
    - run: dockerBuild hdlc/ghdl      ghdl

    - run: dockerTestPkg ghdl
    - run: dockerTest  hdlc/ghdl      ghdl

    - name: Login to DockerHub
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - run: dockerPush  hdlc/pkg:ghdl
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'

    - run: dockerPush  hdlc/ghdl
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'
