name: 'ghdl'

on:
  push:
  schedule:
    - cron: '0 0 * * 5'
  repository_dispatch:
    types: [ ghdl ]

jobs:

  ghdl:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build images
      run: |
        docker build -t hdlc/ghdl --target=run - < ghdl.dockerfile
        docker build -t hdlc/ghdl:yosys - < ghdl.dockerfile

    - uses: docker://hdlc/ghdl
      with:
        args: ./test/ghdl.sh

    - uses: docker://hdlc/ghdl:yosys
      with:
        args: ./test/ghdl--yosys.sh

    - name: Deploy to DockerHub
      run: |
        docker push hdlc/ghdl
        docker push hdlc/ghdl:yosys
