name: 'ghdl'

on:
  push:
  schedule:
    - cron: '0 0 * * 5'

jobs:

  ghdl:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build images
      run: |
        docker build -t symbiflow/ghdl --target=run - < ghdl.dockerfile
        docker build -t symbiflow/ghdl:yosys - < ghdl.dockerfile

    - name: Deploy to DockerHub
      run: |
        docker push symbiflow/ghdl
        docker push symbiflow/ghdl:yosys
