name: 'gtkwave'

on:
  push:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:
  repository_dispatch:
    types: [ gtkwave ]

env:
  DOCKER_BUILDKIT: 1

jobs:

  gtkwave:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - run: echo "$(pwd)/.github/bin" >> $GITHUB_PATH

    - run: dockerBuild hdlc/pkg:gtkwave gtkwave

# TODO    - run: dockerTest hdlc/pkg:gtkwave

    - name: Login to DockerHub
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - run: dockerPush hdlc/pkg:gtkwave
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'
