name: 'icestorm'

on:
  push:
  schedule:
    - cron: '0 0 * * 5'
  repository_dispatch:
    types: [ icestorm ]

jobs:

  icestorm:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build images
      run: |
        docker build -t symbiflow/pkg:icestorm --target=pkg - < icestorm.dockerfile
        docker build -t symbiflow/icestorm - < icestorm.dockerfile

    - name: Deploy to DockerHub
      run: |
        docker push symbiflow/pkg:icestorm
        docker push symbiflow/icestorm
