name: 'impl'

on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:
  repository_dispatch:
    types: [ impl ]

env:
  DOCKER_BUILDKIT: 1

jobs:

  impl:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - run: echo "$(pwd)/.github/bin" >> $GITHUB_PATH

    - run: dockerBuild hdlc/impl impl

    - run: dockerTest  hdlc/impl impl

    - name: Login to DockerHub
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - run: dockerPush  hdlc/impl
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'
