name: 'nextpnr'

on:
  push:
  schedule:
    - cron: '0 0 * * 5'
  repository_dispatch:
    types: [ nextpnr ]

jobs:

  nextpnr:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build images
      run: |
        docker build -t hdlc/nextpnr:ice40 --target=ice40 - < nextpnr.dockerfile
        docker build -t hdlc/nextpnr:ecp5 --target=ecp5 - < nextpnr.dockerfile
        docker build -t hdlc/nextpnr - < nextpnr.dockerfile

    - name: Deploy to DockerHub
      run: |
        docker push hdlc/nextpnr:ice40
        docker push hdlc/nextpnr:ecp5
        docker push hdlc/nextpnr
