name: 'nextpnr'

on:
  push:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:
  repository_dispatch:
    types: [ nextpnr ]

env:
  DOCKER_BUILDKIT: 1

jobs:

  nextpnr:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - run: echo "$(pwd)/.github/bin" >> $GITHUB_PATH

    - run: dockerBuild hdlc/nextpnr:ice40       nextpnr ice40
    - run: dockerBuild hdlc/nextpnr:icestorm    nextpnr icestorm
    - run: dockerBuild hdlc/nextpnr:ecp5        nextpnr ecp5
    - run: dockerBuild hdlc/nextpnr:prjtrellis  nextpnr prjtrellis
    - run: dockerBuild hdlc/nextpnr             nextpnr

    - run: dockerTest  hdlc/nextpnr:ice40       nextpnr--ice40
    - run: dockerTest  hdlc/nextpnr:icestorm    nextpnr--icestorm
    - run: dockerTest  hdlc/nextpnr:ecp5        nextpnr--ecp5
    - run: dockerTest  hdlc/nextpnr:prjtrellis  nextpnr--prjtrellis
    - run: dockerTest  hdlc/nextpnr             nextpnr

    - name: Login to DockerHub
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - run: dockerPush  hdlc/nextpnr:ice40
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'

    - run: dockerPush  hdlc/nextpnr:icestorm
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'

    - run: dockerPush  hdlc/nextpnr:ecp5
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'

    - run: dockerPush  hdlc/nextpnr:prjtrellis
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'

    - run: dockerPush  hdlc/nextpnr
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'
