name: 'yosys'

on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:
  repository_dispatch:
    types: [ yosys ]

env:
  DOCKER_BUILDKIT: 1

jobs:

  yosys:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - run: echo "$(pwd)/.github/bin" >> $GITHUB_PATH

    - run: dockerBuild hdlc/pkg:yosys yosys pkg
    - run: dockerBuild hdlc/yosys     yosys

# TODO    - name: dockerTest hdlc/pkg:yosys
    - run: dockerTest  hdlc/yosys     yosys

    - name: Login to DockerHub
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - run: dockerPush  hdlc/pkg:yosys
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'

    - run: dockerPush  hdlc/yosys
      if: github.event_name != 'pull_request' && github.repository == 'hdl/containers'
