name: 'yosys'

on:
  push:
  schedule:
    - cron: '0 0 * * 5'

jobs:

  yosys:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Build images
      run: |
        docker build -t symbiflow/pkg:yosys --target=pkg - < yosys.dockerfile
        docker build -t symbiflow/yosys - < yosys.dockerfile

    - name: Deploy to DockerHub
      run: |
        docker push symbiflow/pkg:yosys
        docker push symbiflow/yosys
